#remote_theme           : "mmistakes/minimal-mistakes@4.17.2"
theme : "jekyll-theme-minimal"
lang  : "ja-JP"
title : "KawamHub on GitHub Page"
description: "スピードキューブ関連情報まとめ"
google_analytics: UA-141207758-2
logo :